name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master  
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
 
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
     
    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile  
        push: true 
        build-args: | 
          AWS_ACCESS_KEY_ID= ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_S3_ENDPOINT_URL= ${{ secrets.AWS_S3_ENDPOINT_URL }}
          AWS_SECRET_ACCESS_KEY= ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_STORAGE_BUCKET_NAME= ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
          PGDATABASE= ${{ secrets.PGDATABASE }}
          PGHOST= ${{ secrets.PGHOST }}
          PGPASSWORD= ${{ secrets.PGPASSWORD }}
          PGUSER= ${{ secrets.PGUSER }}
        tags: sudheer007dfs/ges-backend:v13

    - name: Verify Pushed Image
      run: docker pull sudheer007dfs/ges-backend:v13

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_USERNAMEE}}   
        script: |
          docker-compose stop
          docker-compose rm -f
          docker-compose pull   
          docker-compose up -d 
